import { TakesArgument } from "@framework/arguments/ArgumentTypes";
import UserArgument from "@framework/arguments/UserArgument";
import { Buildable, Command, CommandMessage } from "@framework/commands/Command";
import Context from "@framework/commands/Context";
import { Inject } from "@framework/container/Inject";
import ConfigurationManager from "@main/services/ConfigurationManager";
import InfractionManager from "@main/services/InfractionManager";
import { AttachmentBuilder, User } from "discord.js";
import { GeneratePlainTextExportColumn } from "../../services/InfractionManager";

type SendHistoryCommandArgs = {
    user: User;
};

@TakesArgument<SendHistoryCommandArgs>({
    names: ["user"],
    types: [UserArgument<true>],
    optional: false,
    rules: [
        {
            "interaction:no_required_check": true
        }
    ],
    errorMessages: [UserArgument.defaultErrors],
    interactionName: "user"
})
class SendHistoryCommand extends Command {
    public override readonly name = "sendhistory";
    public override readonly description = "Sends a full list of infractions of a member.";
    public override readonly detailedDescription =
        "Sends a full list of infractions of a member. This includes all warnings, mutes, bans, and other types of infracti";
    public override readonly defer = true;
    public override readonly aliases = ["smh", "sendinfs"];

    @Inject()
    protected readonly infractionManager!: InfractionManager;

    @Inject()
    protected readonly configManager!: ConfigurationManager;

    public override build(): Buildable[] {
        return [
            this.buildChatInput().addUserOption(option =>
                option
                    .setName("user")
                    .setDescription("The user to get the infraction history for.")
                    .setRequired(true)
            )
        ];
    }

    public override async execute(context: Context<CommandMessage>, args: SendHistoryCommandArgs) {
        if (process.isBun) {
            await context.error("This command is not available in a Bun environment.");
            return;
        }

        const { user } = args;

        const columnsToInclude: GeneratePlainTextExportColumn[] = [
            "id",
            "type",
            "moderatorId",
            "reason",
            "duration",
            "deliveryStatus",
            "metadata",
            "createdAt",
            "updatedAt",
            "expiresAt"
        ];

        const { count, output: table } = await this.infractionManager.generatePlainTextExport({
            guild: context.guild,
            user,
            columnsToInclude,
            onlyNotified: false
        });

        if (count === 0) {
            await context.reply("This user has no infractions in this server.");
            return;
        }

        let output = `Date: ${new Date().toUTCString()}\n`;

        output += `Server: ${context.guild.name}\n`;
        output += `User: ${user.username} (${user.id})\n\n`;
        output += `Generated By: SudoBot/${this.application.metadata.version}\n\n`;
        output += table;
        output += "\n";

        await context.success({
            content: "Here is the full list of infractions for this user.",
            files: [
                new AttachmentBuilder(Buffer.from(output)).setName(
                    `${user.username}_infractions.txt`
                )
            ]
        });
    }
}

export default SendHistoryCommand;
