name: Build BlazeBuild

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: blazebuild

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm install -D

      - name: Build with TypeScript
        run: npx tsc
