name: Publish schema package

on:
  push:
    paths:
      - "src/schemas/**"
      - ".github/workflows/publish-schemas.yml"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: cd src/schemas/typescript && npm install

      - name: Build
        run: cd src/schemas/typescript && npm run build

      - name: Run tests
        run: cd src/schemas/typescript && npm test

      - name: Publish
        run: cd src/schemas/typescript && npm publish --provenance --ignore-scripts || true
